---
title: "TxDb.Athaliana.Ensembl.TAIR10"
author: "Kabilan"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{TxDb.Athaliana.Ensembl.TAIR10}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

**TxDb.Athaliana.Ensembl.TAIR10** is a Bioconductor-compatible
transcript annotation package for *Arabidopsis thaliana* based on the
**TAIR10 reference genome**.

The TxDb object was generated from the **Ensembl Plants GFF3 annotation
(Ensembl Plants release 63)**. The annotation includes genomic
coordinates and transcript models for genes, transcripts, exons, and
coding sequences (CDS).

The package is intended for downstream genomic analyses using
Bioconductor packages such as **GenomicFeatures**, **GenomicRanges**,
**Signac**, **ArchR**, and **ChIPseeker**.


``` r
# Installation
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
BiocManager::install(c(
    "AnnotationHub",
    "GenomicFeatures",
    "GenomicRanges"
))
```

# Loading the package


``` r
library(TxDb.Athaliana.Ensembl.TAIR10)
library(GenomicFeatures)
```

```
## Loading required package: S4Vectors
```

```
## Loading required package: stats4
```

```
## 
## Attaching package: 'S4Vectors'
```

```
## The following object is masked from 'package:utils':
## 
##     findMatches
```

```
## The following objects are masked from 'package:base':
## 
##     expand.grid, I, unname
```

```
## Loading required package: IRanges
```

```
## 
## Attaching package: 'IRanges'
```

```
## The following object is masked from 'package:grDevices':
## 
##     windows
```

```
## Loading required package: Seqinfo
```

```
## Loading required package: GenomicRanges
```

```
## Loading required package: AnnotationDbi
```

```
## Loading required package: Biobase
```

```
## Welcome to Bioconductor
## 
##     Vignettes contain introductory material; view with
##     'browseVignettes()'. To cite Bioconductor, see
##     'citation("Biobase")', and for packages
##     'citation("pkgname")'.
```

```
## 
## Attaching package: 'Biobase'
```

```
## The following object is masked from 'package:AnnotationHub':
## 
##     cache
```

``` r
library(GenomicRanges)
```


``` r
# Downloading the TxDb file from AnnotationHub
TxDb.Athaliana.Ensembl.TAIR10 <- tryCatch({
    ah <- AnnotationHub()
    ah[["AH122287"]]
}, error = function(e) NULL)
```

```
## snapshotDate(): 2026-08-14
```

```
## downloading 1 resources
```

```
## retrieving 1 resource
```

```
## loading from cache
```



# Package summary

The TxDb object can be accessed directly after loading the package.


``` r
TxDb.Athaliana.Ensembl.TAIR10
```

```
## TxDb object:
## # Db type: TxDb
## # Supporting package: GenomicFeatures
## # Data source: Ensembl Plants
## # Organism: Arabidopsis thaliana
## # Taxonomy ID: 3702
## # Genome: NA
## # Nb of transcripts: 54013
## # Db created by: txdbmaker package from Bioconductor
## # Creation time: 2026-08-08 14:52:47 +0500 (Sat, 08 Aug 2026)
## # txdbmaker version at creation time: 1.9.0
## # RSQLite version at creation time: 3.53.3
## # DBSCHEMAVERSION: 1.2
```

# Genome and chromosome information

The genome information associated with the TxDb can be inspected using
`seqinfo()`.


``` r
seqinfo(TxDb.Athaliana.Ensembl.TAIR10)
```

```
## Seqinfo object with 7 sequences (2 circular) from an unspecified genome:
##   seqnames seqlengths isCircular genome
##   1          30427671      FALSE   <NA>
##   2          19698289      FALSE   <NA>
##   3          23459830      FALSE   <NA>
##   4          18585056      FALSE   <NA>
##   5          26975502      FALSE   <NA>
##   Mt           366924       TRUE   <NA>
##   Pt           154478       TRUE   <NA>
```

The available chromosome and sequence names can be retrieved using
`seqlevels()`.


``` r
seqlevels(TxDb.Athaliana.Ensembl.TAIR10)
```

```
## [1] "1"  "2"  "3"  "4"  "5"  "Mt" "Pt"
```

The annotation includes the five nuclear chromosomes and the
mitochondrial and plastid sequences of the TAIR10 reference genome.

# Gene annotations

All annotated genes can be retrieved using `genes()`.


``` r
genes(TxDb.Athaliana.Ensembl.TAIR10)
```

```
## GRanges object with 32833 ranges and 1 metadata column:
##             seqnames        ranges strand |     gene_id
##                <Rle>     <IRanges>  <Rle> | <character>
##   AT1G01010        1     3631-5899      + |   AT1G01010
##   AT1G01020        1     6788-9130      - |   AT1G01020
##   AT1G01030        1   11649-13714      - |   AT1G01030
##   AT1G01040        1   23121-31227      + |   AT1G01040
##   AT1G01046        1   28500-28706      + |   AT1G01046
##         ...      ...           ...    ... .         ...
##   ATMG09730       Mt 181268-181347      + |   ATMG09730
##   ATMG09740       Mt 191954-192025      - |   ATMG09740
##   ATMG09950       Mt 333651-333725      - |   ATMG09950
##   ATMG09960       Mt 347266-347348      + |   ATMG09960
##   ATMG09980       Mt 359666-359739      - |   ATMG09980
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
```

# Transcript annotations

Transcript models can be retrieved using `transcripts()`.


``` r
head(transcripts(TxDb.Athaliana.Ensembl.TAIR10))
```

```
## GRanges object with 6 ranges and 2 metadata columns:
##       seqnames      ranges strand |     tx_id     tx_name
##          <Rle>   <IRanges>  <Rle> | <integer> <character>
##   [1]        1   3631-5899      + |         1 AT1G01010.1
##   [2]        1 11101-11372      + |         2 AT1G03987.1
##   [3]        1 23121-31227      + |         3 AT1G01040.1
##   [4]        1 23416-31120      + |         4 AT1G01040.2
##   [5]        1 28500-28706      + |         5   at1g01046
##   [6]        1 32727-33009      + |         6 AT1G03997.1
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
```

# Exon annotations

Exon coordinates can be retrieved using `exons()`.


``` r
head(exons(TxDb.Athaliana.Ensembl.TAIR10))
```

```
## GRanges object with 6 ranges and 1 metadata column:
##       seqnames    ranges strand |   exon_id
##          <Rle> <IRanges>  <Rle> | <integer>
##   [1]        1 3631-3913      + |         1
##   [2]        1 3996-4276      + |         2
##   [3]        1 4486-4605      + |         3
##   [4]        1 4706-5095      + |         4
##   [5]        1 5174-5326      + |         5
##   [6]        1 5439-5899      + |         6
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
```

# Coding sequence (CDS) annotations

Coding sequence coordinates can be retrieved using `cds()`.


``` r
head(cds(TxDb.Athaliana.Ensembl.TAIR10))
```

```
## GRanges object with 6 ranges and 1 metadata column:
##       seqnames    ranges strand |    cds_id
##          <Rle> <IRanges>  <Rle> | <integer>
##   [1]        1 3760-3913      + |         1
##   [2]        1 3996-4276      + |         2
##   [3]        1 4486-4605      + |         3
##   [4]        1 4706-5095      + |         4
##   [5]        1 5174-5326      + |         5
##   [6]        1 5439-5630      + |         6
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
```

# Promoter regions

Promoter regions can be defined relative to transcription start sites
using the `promoters()` accessor.

For example, the following extracts regions extending 2 kb upstream and
200 bp downstream of transcription start sites.


``` r
head(promoters(
    TxDb.Athaliana.Ensembl.TAIR10,
    upstream = 2000,
    downstream = 200
))
```

```
## Warning in valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE): GRanges 
object contains 7 out-of-bound ranges located on
##   sequences 2, 3, and 5. Note that ranges located on a
##   sequence whose length is unknown (NA) or on a circular
##   sequence are not considered out-of-bound (use seqlengths()
##   and isCircular() to get the lengths and circularity flags
##   of the underlying sequences). You can use trim() to trim
##   these ranges. See ?`trim,GenomicRanges-method` for more
##   information.
```

```
## GRanges object with 6 ranges and 2 metadata columns:
##               seqnames      ranges strand |     tx_id
##                  <Rle>   <IRanges>  <Rle> | <integer>
##   AT1G01010.1        1   1631-3830      + |         1
##   AT1G03987.1        1  9101-11300      + |         2
##   AT1G01040.1        1 21121-23320      + |         3
##   AT1G01040.2        1 21416-23615      + |         4
##     at1g01046        1 26500-28699      + |         5
##   AT1G03997.1        1 30727-32926      + |         6
##                   tx_name
##               <character>
##   AT1G01010.1 AT1G01010.1
##   AT1G03987.1 AT1G03987.1
##   AT1G01040.1 AT1G01040.1
##   AT1G01040.2 AT1G01040.2
##     at1g01046   at1g01046
##   AT1G03997.1 AT1G03997.1
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
```

# Transcripts grouped by gene

Transcripts can be grouped according to their parent genes using
`transcriptsBy()`.


``` r
tx_by_gene <- GenomicFeatures::transcriptsBy(
    TxDb.Athaliana.Ensembl.TAIR10,
    by = "gene"
)

tx_by_gene
```

```
## GRangesList object of length 32833:
## $AT1G01010
## GRanges object with 1 range and 2 metadata columns:
##       seqnames    ranges strand |     tx_id     tx_name
##          <Rle> <IRanges>  <Rle> | <integer> <character>
##   [1]        1 3631-5899      + |         1 AT1G01010.1
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
## 
## $AT1G01020
## GRanges object with 6 ranges and 2 metadata columns:
##       seqnames    ranges strand |     tx_id     tx_name
##          <Rle> <IRanges>  <Rle> | <integer> <character>
##   [1]        1 6788-8737      - |      7164 AT1G01020.2
##   [2]        1 6788-8737      - |      7165 AT1G01020.6
##   [3]        1 6788-9130      - |      7166 AT1G01020.1
##   [4]        1 6788-9130      - |      7167 AT1G01020.3
##   [5]        1 6788-9130      - |      7168 AT1G01020.4
##   [6]        1 6788-9130      - |      7169 AT1G01020.5
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
## 
## $AT1G01030
## GRanges object with 2 ranges and 2 metadata columns:
##       seqnames      ranges strand |     tx_id     tx_name
##          <Rle>   <IRanges>  <Rle> | <integer> <character>
##   [1]        1 11649-13714      - |      7170 AT1G01030.1
##   [2]        1 11649-13714      - |      7171 AT1G01030.2
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
## 
## ...
## <32830 more elements>
```

# Exons grouped by transcript

Exons can be grouped by transcript using `exonsBy()`.


``` r
exonsBy(
    TxDb.Athaliana.Ensembl.TAIR10,
    by = "tx"
)
```

```
## GRangesList object of length 54013:
## $`1`
## GRanges object with 6 ranges and 3 metadata columns:
##       seqnames    ranges strand |   exon_id         exon_name
##          <Rle> <IRanges>  <Rle> | <integer>       <character>
##   [1]        1 3631-3913      + |         1 AT1G01010.1.exon1
##   [2]        1 3996-4276      + |         2 AT1G01010.1.exon2
##   [3]        1 4486-4605      + |         3 AT1G01010.1.exon3
##   [4]        1 4706-5095      + |         4 AT1G01010.1.exon4
##   [5]        1 5174-5326      + |         5 AT1G01010.1.exon5
##   [6]        1 5439-5899      + |         6 AT1G01010.1.exon6
##       exon_rank
##       <integer>
##   [1]         1
##   [2]         2
##   [3]         3
##   [4]         4
##   [5]         5
##   [6]         6
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
## 
## $`2`
## GRanges object with 1 range and 3 metadata columns:
##       seqnames      ranges strand |   exon_id
##          <Rle>   <IRanges>  <Rle> | <integer>
##   [1]        1 11101-11372      + |         7
##               exon_name exon_rank
##             <character> <integer>
##   [1] AT1G03987.1.exon1         1
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
## 
## ...
## <54011 more elements>
```

# Gene models for downstream analysis

The TxDb can be used as a source of genomic coordinates for downstream
Bioconductor workflows. For example, gene and transcript coordinates can
be converted to `GRanges` objects and used with other genomic datasets.


``` r
gene_ranges <- genes(TxDb.Athaliana.Ensembl.TAIR10)

gene_ranges
```

```
## GRanges object with 32833 ranges and 1 metadata column:
##             seqnames        ranges strand |     gene_id
##                <Rle>     <IRanges>  <Rle> | <character>
##   AT1G01010        1     3631-5899      + |   AT1G01010
##   AT1G01020        1     6788-9130      - |   AT1G01020
##   AT1G01030        1   11649-13714      - |   AT1G01030
##   AT1G01040        1   23121-31227      + |   AT1G01040
##   AT1G01046        1   28500-28706      + |   AT1G01046
##         ...      ...           ...    ... .         ...
##   ATMG09730       Mt 181268-181347      + |   ATMG09730
##   ATMG09740       Mt 191954-192025      - |   ATMG09740
##   ATMG09950       Mt 333651-333725      - |   ATMG09950
##   ATMG09960       Mt 347266-347348      + |   ATMG09960
##   ATMG09980       Mt 359666-359739      - |   ATMG09980
##   -------
##   seqinfo: 7 sequences (2 circular) from an unspecified genome
```

# Session information


``` r
sessionInfo()
```

```
## R version 4.6.1 (2026-06-24 ucrt)
## Platform: x86_64-w64-mingw32/x64
## Running under: Windows 11 x64 (build 26200)
## 
## Matrix products: default
##   LAPACK version 3.12.1
## 
## locale:
## [1] LC_COLLATE=English_India.utf8 
## [2] LC_CTYPE=English_India.utf8   
## [3] LC_MONETARY=English_India.utf8
## [4] LC_NUMERIC=C                  
## [5] LC_TIME=English_India.utf8    
## 
## time zone: Asia/Calcutta
## tzcode source: internal
## 
## attached base packages:
## [1] stats4    stats     graphics  grDevices utils    
## [6] datasets  methods   base     
## 
## other attached packages:
##  [1] GenomicFeatures_1.65.0              
##  [2] AnnotationDbi_1.74.0                
##  [3] Biobase_2.73.2                      
##  [4] GenomicRanges_1.64.0                
##  [5] Seqinfo_1.2.0                       
##  [6] IRanges_2.46.0                      
##  [7] S4Vectors_0.50.1                    
##  [8] TxDb.Athaliana.Ensembl.TAIR10_0.99.0
##  [9] knitr_1.51                          
## [10] AnnotationHub_4.2.2                 
## [11] BiocFileCache_3.2.0                 
## [12] dbplyr_2.6.0                        
## [13] BiocGenerics_0.58.1                 
## [14] generics_0.1.4                      
## 
## loaded via a namespace (and not attached):
##  [1] SummarizedExperiment_1.42.0 KEGGREST_1.53.6            
##  [3] rjson_0.2.23                xfun_0.60                  
##  [5] httr2_1.3.0                 lattice_0.22-9             
##  [7] vctrs_0.7.3                 tools_4.6.1                
##  [9] bitops_1.1-0                parallel_4.6.1             
## [11] curl_7.1.0                  tibble_3.3.1               
## [13] RSQLite_3.53.3              blob_1.3.0                 
## [15] pkgconfig_2.0.3             Matrix_1.7-6               
## [17] cigarillo_1.3.1             lifecycle_1.0.5            
## [19] compiler_4.6.1              Rsamtools_2.29.0           
## [21] Biostrings_2.80.1           codetools_0.2-20           
## [23] htmltools_0.5.9             RCurl_1.98-1.19            
## [25] yaml_2.3.12                 pillar_1.11.1              
## [27] crayon_1.5.3                BiocParallel_1.47.0        
## [29] rsconnect_1.10.1            DelayedArray_0.38.2        
## [31] cachem_1.1.0                abind_1.4-8                
## [33] tidyselect_1.2.1            digest_0.6.39              
## [35] dplyr_1.2.1                 purrr_1.2.2                
## [37] restfulr_0.0.17             BiocVersion_3.24.0         
## [39] grid_4.6.1                  fastmap_1.2.0              
## [41] SparseArray_1.13.2          cli_3.6.6                  
## [43] magrittr_2.0.5              S4Arrays_1.13.0            
## [45] XML_3.99-0.23               withr_3.0.3                
## [47] filelock_1.0.3              rappdirs_0.3.4             
## [49] bit64_4.8.2                 rmarkdown_2.31             
## [51] XVector_0.52.0              httr_1.4.8                 
## [53] matrixStats_1.5.0           bit_4.6.0                  
## [55] otel_0.2.0                  png_0.1-9                  
## [57] memoise_2.0.1               evaluate_1.0.5             
## [59] BiocIO_1.22.0               rtracklayer_1.73.0         
## [61] rlang_1.3.0                 glue_1.8.1                 
## [63] DBI_1.3.0                   BiocManager_1.30.27        
## [65] rstudioapi_0.19.0           R6_2.6.1                   
## [67] MatrixGenerics_1.24.0       GenomicAlignments_1.49.1
```
